Traceback (most recent call last):
  File "/home/ubuntu/DE2-GithubAnalytics/consumers/main_repo_consumer.py", line 1, in <module>
    import pulsar
ModuleNotFoundError: No module named 'pulsar'
Traceback (most recent call last):
  File "/home/ubuntu/DE2-GithubAnalytics/consumers/main_repo_consumer.py", line 1, in <module>
    import pulsar
ModuleNotFoundError: No module named 'pulsar'
Traceback (most recent call last):
  File "/home/ubuntu/DE2-GithubAnalytics/consumers/main_repo_consumer.py", line 1, in <module>
    import pulsar
ModuleNotFoundError: No module named 'pulsar'
Traceback (most recent call last):
  File "/home/ubuntu/DE2-GithubAnalytics/consumers/main_repo_consumer.py", line 1, in <module>
    import pulsar
ModuleNotFoundError: No module named 'pulsar'
